version: '3.8'
services:
  changedetection:
    image: dgtlmoon/changedetection.io
    ports:
      - "5000:5000"
    volumes:
      - changedetection-data:/datastore

  monitor:
    build: .
    environment:
      - CHANGEDETECTION_URL=http://changedetection:5000
      - PRODUCT_URL=${PRODUCT_URL}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - APP_PASSWORD=${APP_PASSWORD}
      - CHECK_INTERVAL=${CHECK_INTERVAL:-300}
    depends_on:
      - changedetection
    restart: unless-stopped

volumes:
  changedetection-data: